name: Auto PR, Approve, and Merge from gh-pages

on:
  push:
    branches:
      - gh-pages

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Auto PR from gh-pages"
        title: "Auto PR from gh-pages"
        body: "This is an automated PR created from gh-pages branch."
        branch: gh-pages-pr
        base: main

  approve-pr:
    runs-on: ubuntu-latest
    needs: create-pr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Auto Approve PR
      uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}

  merge-pr:
    runs-on: ubuntu-latest
    needs: approve-pr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const pr_number = parseInt('${{ steps.create_pr.outputs.pull-request-number }}');
          const { data: pr } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number,
          });

          await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number,
            commit_title: `Merging PR #${pr_number}: ${pr.title}`,
            sha: pr.head.sha
          });
