name: Auto-Rebase Base Branch into PR

on:
  pull_request_target:
    types: [auto_merge_enabled] # Runs when PR is set to automerge

jobs:
  rebase_base_branch:
    permissions:
      contents: write  # Allows pushing changes
      pull-requests: write  # Allows modifying PRs
    runs-on: ubuntu-latest
    steps:
      - name: Determine base branch
        id: base
        run: echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase base branch into PR branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin $BASE_BRANCH
          git rebase origin/$BASE_BRANCH || (git rebase --abort && echo "Rebase failed, resolve manually.")

          git push --force-with-lease && echo "Rebase successful!" || echo "Push failed, manual fix needed."
